feat/vo identities api
molgenis/molgenis pull request #9181
Opened 2021-03-11 16:38 UTC by fdlk

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] Migration step added in case of breaking change
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

2021-03-12 08:23 UTC, sidohaakma commented
![](https://github.trello.services/images/mini-trello-icon.png) [identities api](https://trello.com/c/DwlEgfPh/810-identities-api)

2021-03-12 08:53 UTC, sidohaakma requested changes

2021-03-12 08:53 UTC, sidohaakma commented on molgenis-api-identities/src/main/java/org/molgenis/api/identities/VOGroupMemberResponse.java
> +@SuppressWarnings("java:S1610")
Add swagger

2021-03-15 11:02 UTC, fdlk commented
I've upgraded the preview on https://preview-pr-9181-8.dev.molgenis.org/ to build 10

2021-03-15 13:45 UTC, sidohaakma approved these changes

2021-03-15 13:45 UTC, merged