feat: make attribute maxLength configurable
molgenis/molgenis pull request #9199
Opened 2021-04-06 20:44 UTC by fdlk

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] Migration step added in case of breaking change
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

2021-04-07 12:08 UTC, tommydeboer requested changes

2021-04-07 12:11 UTC, fdlk commented on molgenis-data/src/main/java/org/molgenis/data/meta/model/Attribute.java
> +  public Integer getMaxLength() {
Unsure. AttributeType.getMaxLength() does not have the annotation, so all of the reading code is full of assumptions.

2021-04-07 12:21 UTC, fdlk commented on molgenis-data/src/main/java/org/molgenis/data/meta/model/Attribute.java
> +  public Integer getMaxLength() {
I've added the annotation, let's see how angry sonar gets

2021-04-08 06:45 UTC, tommydeboer commented
This might be a forms issue but there's an `undefined` in the error message: 

> Invalid string value 'Dirk de haan' for attribute 'lastName' of entity 'it_emx_autoid_testAutoId'.Value must be less than or equal to 5 characters (undefined)

2021-04-08 06:47 UTC, tommydeboer commented
Man, this feature can be pretty dangerous if you don't know what you're doing! All data already present in the column will be silently truncated if you reduce the `maxLength`.

2021-04-08 07:05 UTC, tommydeboer commented
The forms input for strings can't take strings longer than 255.

2021-04-08 07:06 UTC, tommydeboer commented
Should we add `maxLength` to:
- EMX?
- Metadata Manager?

2021-04-08 07:14 UTC, tommydeboer commented
Hmm maybe the Data Explorer should also truncate very long strings like it does with text fields.

2021-04-08 07:37 UTC, tommydeboer commented
**Issue:** `maxLength` doesn't show up in the metadata manager
1. Import `it_emx_autoid`
2. Set `maxLength` of `lastName` to 10
3. Hit `/api/metadata/it_emx_autoid_testAutoId`

```json
"data": {
  "id": "aaaac6fqlz6kwivhuemmfuaaay",
  "label": "lastName",
  "name": "lastName",
  "sequenceNr": 4,
  "type": "string",
  "idAttribute": false,
  "labelAttribute": false,
  "nullable": true,
  "auto": false,
  "visible": true,
  "unique": false,
  "readOnly": false,
  "aggregatable": false
}
```

2021-04-09 07:48 UTC, tommydeboer approved these changes

2021-04-09 07:48 UTC, merged