feat: simple expressions
molgenis/molgenis pull request #9238
Opened 2021-05-05 22:15 UTC by fdlk

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] Migration step added in case of breaking change
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

2021-06-03 14:12 UTC, tommydeboer requested changes

2021-06-03 14:12 UTC, tommydeboer commented on molgenis-data/src/main/java/org/molgenis/data/meta/model/AttributeMetadata.java
> -  private static String getMappedByValidationExpression() {
YES!!! Bye byeeee

2021-06-03 14:12 UTC, tommydeboer commented on molgenis-security/src/main/java/org/molgenis/security/settings/AuthenticationSettingsImpl.java
> +          .setValidationExpression("{oidcClients} empty or {sign_in_2fa} = 'Disabled'");
Use `TwoFactorAuthenticationSetting.DISABLED.getLabel()` instead of the value directly

2021-06-07 10:21 UTC, fdlk commented on molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityValidator.java
> +    if (valid != Boolean.TRUE) {
Not happy with this, will refactor

2021-06-08 06:52 UTC, tommydeboer requested changes
MagmaScript is still referenced in the docs:

- https://molgenis.gitbook.io/molgenis/data-management/guide-emx#optional-columns-can-be-omitted
- https://molgenis.gitbook.io/molgenis/data-management/guide-questionnaire#minimal-example

2021-06-15 13:37 UTC, tommydeboer commented
![image](https://user-images.githubusercontent.com/5362890/122061869-341b1500-cdef-11eb-9932-cd190fbdc2ef.png)
The examples in the Metadata Manager still show Magma

2021-06-16 08:14 UTC, fdlk commented
> ![image](https://user-images.githubusercontent.com/5362890/122061869-341b1500-cdef-11eb-9932-cd190fbdc2ef.png)
> The examples in the Metadata Manager still show Magma

Moved to molgenis-frontend repo

2021-06-17 15:25 UTC, fdlk commented
![Schermafbeelding 2021-06-17 om 17 24 55](https://user-images.githubusercontent.com/1523838/122426969-fce46980-cf90-11eb-8df0-952eddf17909.png)

2021-07-02 08:46 UTC, tommydeboer approved these changes

2021-07-02 08:48 UTC, merged